version: 2.1

jobs:
  deploy:
    working_directory: ~/yutafujii0/serverless-quote-service
    docker:
      - image: 'cimg/node:12.20.0'
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: node --version
      - run: yarn global add serverless
      - run: yarn -i
      - run: /home/circleci/.yarn/bin/serverless deploy --stage dev

workflows:
  main:
    jobs:
      - deploy:
          context: dockerhub
          filters:
            branches:
              only: master
