version: 2.1

jobs:
  deploy:
    working_directory: ~/yutafujii0/serverless-quote-service
    docker:
      - image: 'cimg/node:12'
        auth:
          username: yutafujii
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: node --version
      - run: export PATH="$PATH:$(yarn global bin)"
      - run: yarn global add serverless
      - run: yarn -i
      - run: sls deploy --stage dev

workflows:
  main:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
